version: 2
jobs:
  build:
    docker: #  the docker executor type; machine and macos executors are also supported
      - image: circleci/node:10.0.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: npm install 
      - run: npm start & # run in the background
      - run: npm test 
      - deploy:
          name: digital-ocean
          command: ssh -o "StrictHostKeyChecking no" root@68.183.27.134 "cd ~/circleciexpress; git pull; npm install; forever start server.js"
  