version: 2
jobs:
  build:
    working_directory: /usr/src
    docker:
      - image: circleci/node:4.8.2-jessie
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - run:
          name: install-npm-wee
          command: npm install


workflows:
  version: 2
  build:
    jobs:
      - build